spring:
  application:
    name: microservice-user-center
logging:
  level:
    com.netflix: info
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8761/eureka/,http://peer1:8761/eureka/

